# Backend: FastAPI
FROM python:3.10-slim

WORKDIR /app

# Copy only backend code + requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ /app/src
COPY model.pkl /app/src/model.pkl

EXPOSE 8000

CMD ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000"]